feat(commitlint): remove external dependencies from source `commitlint`
jose-elias-alvarez/null-ls.nvim pull request #1107
Opened 2022-09-14 14:39 UTC by kaiuri

Previous version of this source depended on `@commitlint/config-conventional` and `commitlint-format-json`.

Signed-off-by: Uriel C. A. Fernandes <uriel.acioli@gmail.com>

2022-09-15 03:36 UTC, jose-elias-alvarez reviewed
Looks good overall! I think it's good to remove a dependency, especially since this linter is already a pain to configure. I think we can go ahead and remove the commented-out sections, too.

2022-09-15 03:36 UTC, jose-elias-alvarez commented on lua/null-ls/builtins/diagnostics/commitlint.lua
> +        -- ['^ⓘ'] = vim.diagnostic.severity.INFO
What do you mean by this? Are you saying this symbol can't be parsed?

2022-09-15 03:36 UTC, jose-elias-alvarez commented on lua/null-ls/builtins/diagnostics/commitlint.lua
> +        args = { "-g", vim.fs.normalize("~/.commitlintrc.json"), "--edit", "$FILENAME" },
Generally, we have avoided defining default config paths like this, since for users to define their own config paths, they need to override all the arguments. I would rather have users configure this using `extra_args` . We can mention the need to specify a config path in the documentation and provide an example. 

Edit: it also seems like we can leave this off and `commitlint` will automatically resolve the config file from its `cwd` - maybe that's because it's using a temp file now, in which case that change makes sense.

2022-09-15 03:36 UTC, jose-elias-alvarez commented on lua/null-ls/builtins/diagnostics/commitlint.lua
> +            [=[Needs a `commitlintrc.json` configuration file, [schema](https://json.schemastore.org/commitlintrc.json).]=],
It seems like [the configuration can also be a JavaScript file](https://commitlint.js.org/#/reference-configuration).

2022-09-15 03:36 UTC, jose-elias-alvarez commented on lua/null-ls/builtins/diagnostics/commitlint.lua
> +        to_temp_file = true,
Was this change necessary? It seems to have good `stdin` support.

2022-09-15 03:36 UTC, jose-elias-alvarez commented on lua/null-ls/builtins/diagnostics/commitlint.lua
> +    local valid_line = line:match("]$") and line
I noticed while testing that the errors created when `commitlint` fails to run aren't handled, most likely because of this check. For example, this output: 

```
✖   Please add rules to your `commitlint.config.js`
    - Getting started guide: https://commitlint.js.org/#/?id=getting-started
    - Example config: https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/index.js [empty-rules]

✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

Results in just a single diagnostic: 

```
{ {
    bufnr = 4,
    code = "[empty-rules]",
    col = 0,
    end_col = 0,
    end_lnum = 1,
    filename = "",
    lnum = 0,
    message = " - Example config: https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/index.js ",
    row = 1,
    severity = 2,
    source = "commitlint"
  } }
```

I wonder if there's a better way to check this than to match against the closing bracket. For reference, the current JSON implementation does handle this properly, and I think it would be useful to show the information, since this linter has so many weird pitfalls that can cause it to not work.

2022-09-15 14:34 UTC, kaiuri commented on lua/null-ls/builtins/diagnostics/commitlint.lua
> +        -- ['^ⓘ'] = vim.diagnostic.severity.INFO
It can be parsed, but its message is always the same

```
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
```

I thought it best to leave it commented out until we figure out where to put that message.

2022-09-15 15:05 UTC, kaiuri commented on lua/null-ls/builtins/diagnostics/commitlint.lua
> +    local valid_line = line:match("]$") and line
This linter does have _many_ weird pitfalls. Using it through its API, its raw output is actually a .json object.

Given this commit message:

```
feaT:   
```

When called from a script, commitlint's linter, `@commitlint/lint`, outputs:

```json
{
  "valid": false,
  "errors": [
    {
      "level": 2,
      "valid": false,
      "name": "subject-empty",
      "message": "subject may not be empty"
    },
    {
      "level": 2,
      "valid": false,
      "name": "type-empty",
      "message": "type may not be empty"
    }
  ],
  "warnings": [],
  "input": "feaT:"
}
```

To get reproduce it:

If we can get the raw output... Will do some research here.

2022-09-15 15:08 UTC, kaiuri commented on lua/null-ls/builtins/diagnostics/commitlint.lua
> +    local valid_line = line:match("]$") and line
I think there is. I'd suggest, instead of matching lines, getting the `raw` output and splitting its contents by ourselves.

2022-09-15 15:12 UTC, kaiuri commented on lua/null-ls/builtins/diagnostics/commitlint.lua
> +        args = { "-g", vim.fs.normalize("~/.commitlintrc.json"), "--edit", "$FILENAME" },
It does, we should remove that argument.

2022-09-15 15:19 UTC, kaiuri commented on lua/null-ls/builtins/diagnostics/commitlint.lua
> +            [=[Needs a `commitlintrc.json` configuration file, [schema](https://json.schemastore.org/commitlintrc.json).]=],
I've removed the configuration note as the `-g` option is unneeded because of the temp file. Will leave a link at `doc/BUILTINS.md` as a reference for users.

2022-09-16 02:11 UTC, jose-elias-alvarez commented on lua/null-ls/builtins/diagnostics/commitlint.lua
> +    local valid_line = line:match("]$") and line
This would be ideal, but do you think it's possible? It may be worth opening an issue on their repository. The default CLI output is remarkably unfriendly to parsers, so any other format would be an improvement.

2022-09-16 14:13 UTC, kaiuri commented on lua/null-ls/builtins/diagnostics/commitlint.lua
> +    local valid_line = line:match("]$") and line
### Parsing the raw string

Because of Lua's snappiness I suppose parsing the raw string would _not_ have too much of an overhead and parsing it raw would be a matter of:

1. Identifying `⧗` and disposing of its line.
2. Identifying `✖`/`⚠` and reading thru the string until the next `✖`/`⚠`, each reading than could be considered a diagnostics string and be parsed accordingly.
3. Appending the `ⓘ...` chunk to the end of each diagnostic parsed above on its message field.

I'll give this a try once I have some time to spare, probably today or tomorrow.

---

### Extra thoughts

#### Outputting parser-friendly diagnostics

On account on making the `@commitlint/cli` output raw diagnostics, I'm not sure it's possible. Skimming over its source code, I've found both `@commitlint/cli` and `@commitlint/format` - the latter which is responsible for the unfriendly output - to be deeply coupled together. Though putting together a CLI that just lints but does not format isn't hard, [here](https://gist.github.com/kaiuri/2461997d54b2768225177f71880e199a)'s a tiny gist how it'd might be done.

I fear this would all be out of `null-ls.nvim`'s scope, though its could work with through a neovim's node_provider. Though, sadly it doesn't work with `pnpm` and I'm kind of locked out on this one.

2022-09-17 03:07 UTC, jose-elias-alvarez commented on lua/null-ls/builtins/diagnostics/commitlint.lua
> +    local valid_line = line:match("]$") and line
Interesting idea! As you say I think it's out-of-scope for us here, but I think it's worth at least opening an issue upstream and seeing if there's interest, since I'm sure other integrations would appreciate it.

2022-09-18 17:44 UTC, kaiuri commented
### Update

Managed to parse each message from `format = "raw"`. Now I'm looking to parse each message's severity so as not to output a bunch of same severity messages.

2022-09-26 14:36 UTC, kaiuri commented
@jose-elias-alvarez, Sorry for the delay, it's been a busy few days. Before I commit anything I'd like your opinion on this chunk I wrote that parses multi line `@commitlint/cli` messages. Any suggestions, perceived bottlenecks you might find or anything really.

```lua
local COMMIT_MSG = [[
✖   Please add rules to your `commitlint.config.js`
    - Getting started guide: https://commitlint.js.org/#/?id=getting-started
    - Example config: https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/index.js [empty-rules]

✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
]]

---Checks if a line is the start of a diagnostic's message or not.
---@param line string
---@return boolean
local function message_start(line)
    local symbols = {
        error = "✖",
        warn  = "⚠",
        hint  = "ⓘ",
        info  = "⧗",
    }
    if line == nil then return false end

    local line_start = line:sub(1, 3) -- each symbol has length 3
    for _, v in pairs(symbols) do
        if line_start == v then
            return true
        end
    end

    return false
end

---Parses @commitlint/cli's raw output into single messages that can later be categorized by severity.
---@param output string
---@return string[]
local function parse(output)

    ---@type string[]: Non-empty string array.
    local lines = vim.tbl_filter(function(s)
        return s ~= "" and true or false
    end, vim.split(output, "\n"))

    ---@type string[]: Array of diagnostic messages.
    local messages = {}
    for i = 1, #lines do
        local message = ""
        local curr_line = lines[i]
        if message_start(curr_line) then
            message = message .. curr_line

            --- Go to next line, but only do anything if we're on the same message, else, go back up
            i = i + 1
            while not message_start(lines[i])
                and lines[i] ~= nil do
                message = message
                    .. "\n" -- keep message formatting
                    .. lines[i]
                i = i + 1
            end
        end

        table.insert(messages, message)
    end

    return messages
end

local parsed = parse(COMMIT_MSG)
for _, v in pairs(parsed) do
    print(v)
end

--[[ OUTPUT:
✖   Please add rules to your `commitlint.config.js`
    - Getting started guide: https://commitlint.js.org/#/?id=getting-started
    - Example config: https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/index.js [empty-rules]
✖   found 1 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
]]
```

2022-09-26 15:54 UTC, kaiuri commented
@jose-elias-alvarez, it's done, looking forward to your review.

2022-09-26 23:01 UTC, jose-elias-alvarez commented
Not a problem, I'm also having a busy week on my end but will review when I can!

2022-10-01 00:14 UTC, jose-elias-alvarez requested changes
This is an impressive piece of work, but honestly I'm not 100% sure this approach is worth the headache. Here is the output from a bad commit message with this PR:

<img width="815" alt="Screen Shot 2022-09-30 at 8 11 12 PM" src="https://user-images.githubusercontent.com/54108223/193373201-e9c809f3-ceb6-4462-8444-838427b54cd4.png">

And here is the output with the current JSON implementation (note the error on the 2nd line):

<img width="631" alt="Screen Shot 2022-09-30 at 8 09 38 PM" src="https://user-images.githubusercontent.com/54108223/193373308-82cf1145-aab2-45c8-8744-4c122cb364c2.png">

I suspect that your time and skills would be better put to use contributing a sane, parseable CLI output format to `commitlint` itself (which would benefit other consumers, too). I would love to remove the extra dependency here, but as it stands, I think this needs more work (and ideally a lot of test coverage) to match the current implementation.

2022-10-01 00:14 UTC, jose-elias-alvarez commented on lua/null-ls/builtins/diagnostics/commitlint.lua
> +            message = message:match("%s%s%s(.*)"),
```suggestion
            message = message:match("%s%s%s(.*)") or "",
```

This caused issues for me, since Neovim expects this to always be defined.

2022-10-01 16:01 UTC, kaiuri commented on lua/null-ls/builtins/diagnostics/commitlint.lua
> +            message = message:match("%s%s%s(.*)"),
Thanks for the compliment! I agree. I'm of the opinion short is always best, therefore maybe is best to keep using the previous `built-in` version.
I'll look into contributing a sensible, parseable CLI, output format to `@commitlint/cli`.

Thanks for the review @jose-elias-alvarez

2022-12-10 20:32 UTC, jose-elias-alvarez commented
Closing this and the parent issue for the reasons discussed above. Thanks again!

2022-12-10 20:32 UTC, closed without merging