fix(logger): configurable logging behavior
jose-elias-alvarez/null-ls.nvim pull request #335
Opened 2021-11-11 17:16 UTC by kylo252

- Set the correct stack level in plenary.log
- Use all the levels of logging with the ability of using the console
- Switch `echo_error` to use `Log:warn()`
- Switch most of `u.debug_log()` to `Log:trace()` while keeping some of them as `Log:debug()`

Fixes #280

- fix(logger): configurable logging behavior
- fix(logger): restore the quick debug toggle
- fix(logger): rebase
- chore: use lower-case for logger instances
- fix(logger): explicit mention of empty completion
- chore: naming convention

2021-11-11 17:58 UTC, kylo252 commented
> 1. Moving the detailed description of log configuration out of the basic FAQ to avoid confusion

Yeah, that's always fine. I just didn't know what where it should go.

> 2. No logging at all by default
> 3. Logging defaults to a file, not the console
> 4. Always output critical warnings and errors to the console, regardless of the user's settings

I feel like I'm missing something here. When `log:error` gets triggered it will output to **both** the file, and the console by default.
Here's a screenshot comparison.

![image](https://user-images.githubusercontent.com/59826753/141342813-29bda1ba-b82d-4cd4-93d3-0a6837bfe96f.png)

The one at the top is using the logger, you can tell by the timestamp, while the one on the bottom is using just the `main` branch. The difference is that now I can actually show you this one as well, because it got recorded. Please note that only warnings and errors are shown in either the console or the file, because the logger will simply ignore the request if it doesn't fall within the configured level (note: I had a bug in the code that was ignoring that log-level 😅)

```logtalk
[ERROR Thu 11 Nov 2021 06:30:45 PM CET] ...e/pack/packer/start/null-ls.nvim/lua/null-ls/helpers.lua:164: command markdownlint is not executable (make sure it's installed and on your $PATH)
[WARN  Thu 11 Nov 2021 06:30:50 PM CET] ...site/pack/packer/start/null-ls.nvim/lua/null-ls/loop.lua:99: command timed out after 5000 ms
```

Now let's consider that something a bit more tricky is happening, and you want to see why `prettier` is hanging, then I can turn the logging up a notch to `debug` and either monitor the console or the logfile directly. Or take it to the max and use `trace` level.

This is just a QoL change for everyone involved, for you as the plugin author, and for me as both as a user of your plugin and in the context of maintaining LunarVim.

Of course, it's all up to you at the end, I just figured I need to give you a more concrete example. I can also do another recording if you think it's useful.

2021-11-12 00:18 UTC, jose-elias-alvarez requested changes
Thanks for clarifying the rationale behind these changes. Apart from the comments and a few merge conflicts, I ran into an issue while testing this locally with `debug = true`. The output from formatters fills up the whole screen every time I format the file, which is pretty annoying when combined with formatting on save. 

I think changing `debug = true` so that it both sets the appropriate log level and disables `use_console` is a sensible solution, especially since I think users would appreciate the option to copy-paste the log output from `:NullLsLog`.

2021-11-12 00:18 UTC, jose-elias-alvarez commented on README.md
> +- Enable debug logging
I strongly prefer for this to only mention the `debug` option. Given that setting `debug = true` will output everything to the console unless otherwise specified, I think we can trim down these instructions to just mention `:messages` and the new `:NullLsLog` command.

2021-11-12 00:18 UTC, jose-elias-alvarez commented on lua/null-ls/completion.lua
> +                    log:debug("no results were received completion results from generators")
```suggestion
                    log:debug("received no completion results from generators")
```

2021-11-12 00:18 UTC, jose-elias-alvarez commented on lua/null-ls/formatting.lua
> +    log:debug("received edits from generators:")
```suggestion
    log:debug("received edits from generators")
```

2021-11-12 00:18 UTC, jose-elias-alvarez commented on lua/null-ls/formatting.lua
> +    log:debug("successfully applied edits:")
```suggestion
    log:debug("successfully applied edits")
```

2021-11-12 00:18 UTC, jose-elias-alvarez commented on lua/null-ls/loop.lua
> +            log:warn("command timed out after " .. timeout .. " ms")
Could we also add the name of the command here?

2021-11-12 00:18 UTC, jose-elias-alvarez commented on lua/null-ls/config.lua
> +        use_console = "sync",
Is there any disadvantage to setting this to `sync` by default?

2021-11-12 00:18 UTC, jose-elias-alvarez commented on lua/null-ls/helpers.lua
> +            log:error(
Yes, this needs to prevent the generator from running. Since all of the `validate` statements will already throw errors, I think it's fine to change this back to `assert`. We can wrap `validate_opts` in `pcall` and catch the error so we can log it, but that's a bigger change so we can leave it out of this PR.

2021-11-12 03:20 UTC, jose-elias-alvarez commented
Also, I forgot to mention, but you might have seen how in the new completion source, we are using the `debug` flag to run some additional validation in handlers, and I want to expand this to the other handlers, too. I think keeping `debug` and using it as an all-purpose, tell-me-anything-that-might-be-going-wrong option is still a good idea.

2021-11-12 09:09 UTC, kylo252 commented on README.md
> +- Enable debug logging
How about about something like this? Otherwise, feel free to write it here and and I can just copy it, or you can also push the commit yourself.

2021-11-12 09:11 UTC, kylo252 commented on lua/null-ls/loop.lua
> +            log:warn("command timed out after " .. timeout .. " ms")
Yeah, I've missed this one in the rebase, ` u.debug_log` doesn't exists anymore.

2021-11-12 09:16 UTC, kylo252 commented on lua/null-ls/config.lua
> +        use_console = "sync",
Did you mean `async`? so `async` is faster, but I noticed that it doesn't quite show the errors/warnings in order, if that's something that matters to you. As long as the log level is `warn`/`error` then it doesn't really matter to use `async` because you should seldom have two consecutive errors. I'll set it back to `async` since we moved the `debug` option to be file-only, more or less.

2021-11-12 09:19 UTC, kylo252 commented on lua/null-ls/loop.lua
> +            log:warn("command timed out after " .. timeout .. " ms")
Actually, I'm not sure that we want this one to be a warning because I think it's triggering way too often for my liking. So I'll switch it to be `debug` level, for performance reasons.

2021-11-12 10:01 UTC, kylo252 commented on lua/null-ls/loop.lua
> +            log:warn("command timed out after " .. timeout .. " ms")
what do you think of `on_error()`? I based it on  [/runtime/lua/vim/lsp/rpc.lua#L228](https://github.com//neovim/neovim/blob/29cec32f44db358b0dfcd560d2ba8228b9d9de39/runtime/lua/vim/lsp/rpc.lua#L228), but I'm not sure if you want something more specific.

2021-11-12 10:10 UTC, kylo252 commented on lua/null-ls/helpers.lua
> +            log:error(
I think I found a good middle-ground. Let me know if you don't like it.

2021-11-12 20:50 UTC, jose-elias-alvarez commented on lua/null-ls/loop.lua
> +            log:warn("command timed out after " .. timeout .. " ms")
Sorry, could you clarify what you mean by this? Seeing commands time out should be pretty rare if the command is running properly.

2021-11-12 20:51 UTC, jose-elias-alvarez commented on README.md
> +- Enable debug logging
Seems fine, thanks!

2021-11-13 07:51 UTC, kylo252 commented on lua/null-ls/loop.lua
> +end
@jose-elias-alvarez, This is the new `on_error()` handler I was talking about.
See how it's called in `handle_stdout` and `handle_stderr`.

2021-11-14 19:49 UTC, jose-elias-alvarez commented on lua/null-ls/loop.lua
> +end
I see now, makes sense.

2021-11-14 19:49 UTC, jose-elias-alvarez commented on lua/null-ls/helpers.lua
> +        -- https://github.com/jose-elias-alvarez/null-ls.nvim/pull/335/files#r747896325
```suggestion
```

2021-11-14 19:54 UTC, jose-elias-alvarez approved these changes
Looks good to me! I recently merged a few commits that added more log statements, so could you rebase this against `main`, make sure we've converted everything, and let me know when this is ready to merge?

2021-11-15 09:21 UTC, kylo252 commented
@jose-elias-alvarez, I think that should cover it!

We should defintely add more log entres, but that can be done incrementally afterwards.

2021-11-15 19:03 UTC, jose-elias-alvarez commented
I went ahead and fixed up a few things I noticed while trying this out, but I think it's a nice improvement. Thanks again for your patience and work on this!

2021-11-15 19:03 UTC, merged

2021-11-16 15:56 UTC, jose-elias-alvarez commented
@kylo252 Do you know how to use the `lazy` and `file` methods on the Plenary logger (found [here](https://github.com/nvim-lua/plenary.nvim/blob/1c31adb35fcebe921f65e5c6ff6d5481fa5fa5ac/lua/plenary/log.lua#L177))? I tried the examples in the comments but wasn't able to get them to work. They'd be useful to have.

2021-11-16 19:05 UTC, williamboman commented
I never understood how plenary's lazy log was implemented, it would never print anything. I refactored it a bit to function in a way that I had expected it to. Examples:

```lua
log.lazy_debug(function ()
    local expensive_stuff = do_something()
    return "These return values follow the fmt_debug signature, with placeholders %s", expensive_stuff
end)
```

2021-11-16 19:58 UTC, jose-elias-alvarez commented
@williamboman Thanks for confirming – the nvim-lsp-installer implementation is a lot cleaner and makes more sense than Plenary's, so I'll see how we can fix ours up a bit. 

I'll also see if I can make sense of what Plenary is trying to do and open a PR (or an issue if I can't figure it out).