diagnostics: add semgrep
jose-elias-alvarez/null-ls.nvim pull request #758
Opened 2022-03-14 19:14 UTC by fcsonline

Adding support for SemGrep diagnostics.

https://semgrep.dev/

2022-03-15 00:13 UTC, jose-elias-alvarez requested changes
Looks cool, looking forward to trying this. I pointed out a couple of syntax errors that prevented this from loading, so we'll want to test it out before merging.

2022-03-15 00:13 UTC, jose-elias-alvarez commented on lua/null-ls/builtins/diagnostics/semgrep.lua
> +local methods = require("null-ls.helpers")
```suggestion
local methods = require("null-ls.methods")
```
```suggestion
local methods = require("null-ls.helpers")
```

2022-03-15 00:13 UTC, jose-elias-alvarez commented on lua/null-ls/builtins/diagnostics/semgrep.lua
> +    generator = null_ls.generator({
```suggestion
    generator = helpers.generator_factory({
```

2022-03-15 00:13 UTC, jose-elias-alvarez commented on lua/null-ls/builtins/diagnostics/semgrep.lua
> +    generator = null_ls.generator({
```suggestion
    generator = helpers.generator_factory({
```

2022-03-15 00:13 UTC, jose-elias-alvarez commented on doc/BUILTINS.md
> +- Filetypes: `{ "typescript", "typescriptreact", "ruby", "python", "java", "go" }`
Could you remove the changes to the auto generated files?

2022-03-15 00:13 UTC, jose-elias-alvarez commented on doc/BUILTINS.md
> +- Filetypes: `{ "typescript", "typescriptreact", "ruby", "python", "java", "go" }`
Could you remove the changes to the auto generated files?

2022-03-15 00:13 UTC, jose-elias-alvarez commented on lua/null-ls/builtins/_meta/diagnostics.lua
> +  semgrep = {
This one too, CI will take care of updating it.

2022-03-15 00:13 UTC, jose-elias-alvarez commented on lua/null-ls/builtins/_meta/diagnostics.lua
> +  semgrep = {
This one too, CI will take care of updating it.

2022-03-15 07:22 UTC, fcsonline commented
I'm going to polish a bit and check the style.

2022-03-15 07:39 UTC, fcsonline commented
I think that now it looks much better. :ok_hand:

2022-03-15 07:58 UTC, fcsonline commented
@jose-elias-alvarez  Also, taking the opportunity to say thank you for this awesome nvim plugin. :clap:

2022-03-18 01:48 UTC, jose-elias-alvarez commented
Thanks for putting this together!

2022-03-18 01:48 UTC, merged

2022-06-21 06:41 UTC, xuliefeng commented
hi  I'm using semgrep for java validation, but it's not working as expected. Add print found parsing code results results empty

![image](https://user-images.githubusercontent.com/11550443/174733202-d7db03ce-c3f8-4aeb-a810-592d6471b478.png)

![image](https://user-images.githubusercontent.com/11550443/174733365-d60ea4fa-77b2-4723-9a34-64be6828d07f.png)