feat: make formatting sequential
jose-elias-alvarez/null-ls.nvim pull request #93
Opened 2021-08-08 09:58 UTC by jose-elias-alvarez

Closes #56. Also includes a bunch of changes to generator methods that should not affect anyone and a few changes to debug logs to make them less useless. 

Previously, formatters ran simultaneously, which meant that registering more than one formatter was useless (or worse). This PR makes formatting sequential, meaning that users can register multiple formatters for a given filetype and have them run in the order in which they've been registered.

At the moment, I imagine that most null-ls users are defining built-in formatters in their own configurations, so this won't cause any surprises, but integrations that register formatters should be aware of this change, since spawning processes back-to-back will inevitably slow down formatting.

I work primarily with TypeScript and Lua, where multiple formatters are (mostly) unnecessary, so I'd appreciate feedback from users of languages like Python where multiple formatters seem to be more common (cc @nghialm269, who opened the issue in the first place).

2021-08-08 11:36 UTC, abzcoding commented
cc: @ChristianChiarulli @Tastyep @kylo252

2021-08-08 13:51 UTC, jose-elias-alvarez commented
(Specifically: If anyone can test this as part of an actual workflow and make sure it works as expected, that would be a big help!)

2021-08-08 14:24 UTC, Tastyep requested changes
Nice work :+1:
I tested with LunarVim by configuring both `black` and `isort`, I observed that `black` did run, but not `isort`.
I'll make more tests to see where the problem comes from.

2021-08-08 14:35 UTC, jose-elias-alvarez commented
> Nice work 👍
> I tested with LunarVim by configuring both `black` and `isort`, I observed that `black` did run, but not `isort`.
> I'll make more tests to see where the problem comes from.

That's strange – I'm not sure how LunarVim sets things up, but this was one of the cases I specifically tested and it seems to be working normally for me just by adding each source to `sources` in `null_ls.config`. Maybe it has to do with dynamic registration? I tested it out with a simple `FileType` autocommand and it also seemed to work as expected, though. 

Thanks for the code feedback too! I'll make those changes tomorrow.

2021-08-08 14:38 UTC, Tastyep commented
> > Nice work +1
> > I tested with LunarVim by configuring both `black` and `isort`, I observed that `black` did run, but not `isort`.
> > I'll make more tests to see where the problem comes from.
> 
> That's strange – I'm not sure how LunarVim sets things up, but this was one of the cases I specifically tested and it seems to be working normally for me just by adding each source to `sources` in `null_ls.config`. Maybe it has to do with dynamic registration? I tested it out with a simple `FileType` autocommand and it also seemed to work as expected, though.
> 
> Thanks for the code feedback too! I'll make those changes tomorrow.

You are right, after further testing it seems that the issue comes from us !

2021-08-08 14:46 UTC, jose-elias-alvarez commented
Got it – let me know if there's anything we can do here to make the integration easier.

2021-08-08 14:58 UTC, Tastyep commented
I opened a PR on our side, but I don't understand why the change is needed, maybe you could help us ?

2021-08-08 19:51 UTC, bpinto commented
I'll be testing this with `prettier_d_slim` + `eslint_d` since I override a couple prettier styling rules with aslant ones. A quick test shows it working, but I"ll be testing it this week.

One thing I wondered is if it would be somehow possible to run the formatters (with stdin/stdout support) like a unix pipe so that the file would only be updated once all formatters have finished instead of updating the file once for each configured formatter.

2021-08-09 03:27 UTC, jose-elias-alvarez commented
I think it's possible if we use a temporary buffer. What's the advantage?

2021-08-09 05:05 UTC, jose-elias-alvarez commented on lua/null-ls/generators.lua
> +        if not generators or vim.tbl_isempty(generators) then
I actually moved the function to get registered generators to this file and made sure it always returns a table, so I'll modify this to only check if the table is empty. (`run` is exposed, but if it becomes an issue, validation / better documentation will take care of it.)

2021-08-09 05:12 UTC, jose-elias-alvarez commented on lua/null-ls/generators.lua
> +                    elseif type(results) == "table" then
Makes sense!

2021-08-09 05:20 UTC, jose-elias-alvarez commented on lua/null-ls/generators.lua
> +M.run_sequentially = function(generators, make_params, postprocess, callback)
Strictly speaking it would work in its current state, since `run` can handle an empty table, but it's not exactly clean. I shifted the responsibility for checking if the next generator is `nil` to `run_next`, which should make what's going on a bit clearer.

2021-08-09 06:08 UTC, jose-elias-alvarez commented
@Tastyep I made changes according to your comments and also just pushed a fix that should make `buf.formatting_sync` work, by directly passing the edits to the actual handler and simply returning an empty response to the sync handler afterwards. I think this should make it unnecessary to change the LunarVim formatting event, but let me know what you think and if it works.

2021-08-09 06:53 UTC, Tastyep approved these changes
LGTM, I re-tested with `formatting_sync` and testify that it works.
Let's see if someone finds something while testing more thoroughly.

2021-08-09 08:52 UTC, jose-elias-alvarez commented
The LunarVim issue made me realize that the recommended format on save setup for null-ls actually didn't work properly for actual LSP formatting, so as part of this PR, I'm also removing the `save_after_format` option and updating the recommended instructions to provide a more consistent experience.

2021-08-09 14:45 UTC, bpinto commented
I've been using this branch for hours and it's working 💯.

2021-08-09 16:35 UTC, jose-elias-alvarez commented
Great! So far everything seems to be working well, and (importantly) single-source formatting seems unaffected. I'll review this again tomorrow and merge it.

2021-08-10 09:04 UTC, merged

2021-08-10 09:10 UTC, jose-elias-alvarez commented
Merged! Thanks to everyone for the feedback and testing.